### PR TITLE
UIAlertController

### PR DESCRIPTION
**Pull request by ciscoflores**
This PR:

**Remove**
- UIAlertView -deprecated- as way to display app's error messages, instead add the uses of UIAlertController.

### CODE REVIEW

**Comment by oguzman** [comment]
I'll merge this change (I've already seen how it works) once design team has and give us visual changes. Thanks @ciscoflores.

**Comment by oguzman** [comment]
Checking...

**Comment by ciscoflores** [comment]
LGTM

**Comment by oguzman** [comment]
Ok, I'm merging...

**Pull request merged**
