### PR TITLE
Layout feature

### PR DESCRIPTION
**Pull request by oguzman**
I've updated the layout views for all iPhones, check it out please

### CODE REVIEW

**Comment by oguzman** [comment]
@ciscoflores could you please take a look into this? I need to create a new PR ASAP with a refresh feature; Thanks.

**Comment by ciscoflores** [comment]
Everything works fine, is just a matter of some modifications on the layout side. I'll take care of those changes.

**Comment by oguzman** [comment]
Ok, thanks, let me merge

**Comment by oguzman** [comment]
Done; thanks!

**Pull request merged**
